name: Train

on: [workflow_call]

jobs:
  Train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sambandh/cicd_assignment:v1 .

      - name: Push Docker image to registry
        run: docker push sambandh/cicd_assignment:v1
